### ISSUE TITLE
번역정보 구글시트 보호 요청

### ISSUE THREAD

**Issue by piggykm** [myjung/translate-magicraft#1]
아무나 수정되는거 같습니다. 시트보호좀 걸어주세요! 
그리고 연락방법을 알고 싶어요. 해당 번역데이터를 모드화 시키고 싶습니다.
(현재 r2modman에서 모딩 가능함)

**Comment by myjung** [comment]
안녕하세요. 우선 시트 보호는 걸었고 현재 개발사와 한국 퍼블리셔와 연락이 되어 데이터를 넘기고 정식 한글화 작업중입니다.


아이고 메일로 답장해버렸더니 자동으로 제 개인정보가 기록이 됐었네요 수정했습니다. 연락은 다이렉트로 하시려면 아래 디스코드를 통해주시면 됩니다.

Discord Username : aurelian4857

**Comment by piggykm** [comment]
아! 정식 한글화 작업중이면 모딩 건드릴 필요 없겠네요 감사합니다!
